


const DISCORD_CLIENT_OPTIONS_MAP = {
  default: { partials: ["MESSAGE", "CHANNEL", "REACTION", "USER"], intents: ["GUILD_VOICE_STATES", "GUILDS", "GUILD_MEMBERS", "GUILD_MESSAGES", "GUILD_MESSAGE_REACTIONS"] }
}

module.exports = {DISCORD_CLIENT_OPTIONS_MAP}